version: '3.7'

services:
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    restart: unless-stopped
    ports:
      - ${NGINX_PORT}:80
      - 443:443
    volumes:
      - ${APP_DATA_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     networks:
      - tipi_main_network
    environment:
      - NGINX_PORT=${NGINX_PORT}