version: '3.9'

services:
  pterodactyl-db:
    container_name: pterodactyl-db
    image: mariadb:10.5
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: "panel"
      MYSQL_USER: "pterodactyl"
    networks:
      - tipi_main_network

  pterodactyl-cache:
    container_name: pterodactyl-cache
    image: redis:alpine
    restart: unless-stopped
    networks:
      - tipi_main_network

  pterodactyl:
    image: ghcr.io/pterodactyl/panel:v1.10.1
    container_name: pterodactyl
    restart: unless-stopped
    entrypoint: /bin/sh -c "/config/entrypoint.sh"
    ports:
      - ${APP_PORT}:80
    links:
      - pterodactyl-db
      - pterodactyl-cache
    volumes:
      - ${ROOT_FOLDER_HOST}/apps/pterodactyl/:/config/
      - ${APP_DATA_DIR}/data/var/:/app/var/
      - ${APP_DATA_DIR}/data/nginx/:/etc/nginx/http.d/
      - ${APP_DATA_DIR}/data/certs/:/etc/letsencrypt/
      - ${APP_DATA_DIR}/logs/:/app/storage/logs
    environment:
      APP_URL: http://${INTERNAL_IP}:${APP_PORT}
      APP_TIMEZONE: ${TZ}
      APP_SERVICE_AUTHOR: "noreply@example.com"
      # Uncomment the line below and set to a non-empty value if you want to use Let's Encrypt
      # to generate an SSL certificate for the Panel.
      # LE_EMAIL: ""
      MAIL_FROM: "noreply@example.com"
      MAIL_DRIVER: "smtp"
      MAIL_HOST: "mail"
      MAIL_PORT: "1025"
      MAIL_USERNAME: ""
      MAIL_PASSWORD: ""
      MAIL_ENCRYPTION: "true"
      DB_PASSWORD: ${MYSQL_PASSWORD}
      APP_ENV: "production"
      APP_ENVIRONMENT_ONLY: "false"
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "pterodactyl-cache"
      DB_HOST: "pterodactyl-db"
      DB_PORT: "3306"
      PTERODACTYL_EMAIL: ${PTERODACTYL_EMAIL}
      PTERODACTYL_USERNAME: ${PTERODACTYL_USERNAME}
      PTERODACTYL_PASSWORD: ${PTERODACTYL_PASSWORD}
    networks:
      - tipi_main_network