
version: "3.7"
services:
  adguard:
    image: adguard/adguardhome:v0.107.21
    container_name: adguard
    volumes:
      - "${APP_DATA_DIR}/data/work:/opt/adguardhome/work"
      - "${APP_DATA_DIR}/data/conf:/opt/adguardhome/conf"
    restart: unless-stopped
    networks:
      - tipi_main_network
    ports:
      - ${NETWORK_INTERFACE:-0.0.0.0}:53:53/tcp
      - ${NETWORK_INTERFACE:-0.0.0.0}:53:53/udp
      - ${APP_PORT}:80
    labels:
      traefik.enable: ${APP_EXPOSED}
      traefik.http.routers.adguard.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.adguard.entrypoints: websecure
      traefik.http.routers.adguard.service: adguard
      traefik.http.routers.adguard.tls.certresolver: myresolver
      traefik.http.services.adguard.loadbalancer.server.port: 80
